// Prints SQL that loads src/data/market.ts into public.booths/products.
// Used once to write the 2.0.0 seed migration:
//   node scripts/seed-sql.mjs > supabase/migrations/202610050002_seed_cole_and_mason.sql
import { booth, brand, products } from "../src/data/market.ts";

export const BOOTH_ID = "c01e0000-0000-4000-8000-000000000001";
const SAMPLE_BOOTH_ID = "a6000000-0000-4000-8000-000000000001";

const text = (value) =>
  value === null || value === undefined
    ? "null"
    : `'${String(value).replaceAll("'", "''")}'`;
const textArray = (values) =>
  values.length ? `array[${values.map(text).join(", ")}]` : "'{}'::text[]";

const lines = [
  "begin;",
  "",
  "-- Generated by scripts/seed-sql.mjs from src/data/market.ts (1.5.0 content).",
  "",
  "-- The sample booth from the first migration is no longer shown.",
  `update public.booths set is_active = false where id = '${SAMPLE_BOOTH_ID}';`,
  "",
  "insert into public.booths (id, market_name, name, description, booth_number, location_text, image_path, sort_order, is_active, is_sample, brand)",
  `values ('${BOOTH_ID}', ${text(booth.market_name)}, ${text(booth.name)}, ${text(booth.description)}, ${text(booth.booth_number)}, ${text(booth.location_text)}, ${text(booth.image_path)}, 0, true, ${booth.is_sample}, ${text(JSON.stringify(brand))}::jsonb)`,
  "on conflict (id) do update set market_name = excluded.market_name, name = excluded.name, description = excluded.description,",
  "  booth_number = excluded.booth_number, location_text = excluded.location_text, image_path = excluded.image_path,",
  "  is_active = excluded.is_active, is_sample = excluded.is_sample, brand = excluded.brand, updated_at = now();",
  "",
  "insert into public.products (booth_id, slug, name, category, price, description, image_path, gallery, sort_order)",
  "values",
  products
    .map(
      (p, index) =>
        `  ('${BOOTH_ID}', ${text(p.id)}, ${text(p.name)}, ${text(p.category)}, ${p.price ?? "null"}, ${text(p.description)}, ${text(p.image_path)}, ${textArray(p.gallery ?? [])}, ${index})`,
    )
    .join(",\n"),
  "on conflict (slug) do update set name = excluded.name, category = excluded.category, price = excluded.price,",
  "  description = excluded.description, image_path = excluded.image_path, gallery = excluded.gallery,",
  "  sort_order = excluded.sort_order, updated_at = now();",
  "",
  "commit;",
];
console.log(lines.join("\n"));
